- name: Copy configuration files to Windows targets
  hosts: windows
  gather_facts: no
  tasks:
    - name: Copy ConfigFile.confg to StreamingAssets
      win_copy:
        src: ./config/config.json
        dest: C:\ClassAct\MPGameClient\Classact Dezastru Command Multiplayer VR Disaster_Data\StreamingAssets\config.json

    - name: Copy conf.file to Conf
      win_copy:
        src: ./config/conf.file
        dest: C:\ClassAct\Conf\conf.file

    - name: Copy AllEndpoint.json to Utility\JSON
      win_copy:
        src: ./config/AllEndpoint.json
        dest: C:\ClassAct\MPGameClient\Classact Dezastru Command Multiplayer VR Disaster_Data\StreamingAssets\Utility\JSON\AllEndpoint.json
