- name: Copy and Install ClassAct Dezastru Command
  hosts: windows
  gather_facts: no
  tasks:
    - name: Ensure C:\ClassAct directory exists
      win_file:
        path: C:\ClassAct
        state: directory

    - name: Copy installer files to C:\ClassAct
      win_copy:
        src: "./{{ item }}"
        dest: "C:\\ClassAct\\{{ item }}"
      loop:
        - ClassAct_Dezastru_Command-Installer_V.1.0.exe
        - ClassAct_Dezastru_Command-Installer_V.1.0-1.bin
        - ClassAct_Dezastru_Command-Installer_V.1.0-2.bin
        - ClassAct_Dezastru_Command-Installer_V.1.0-3.bin

    - name: Run ClassAct Dezastru Command installer silently
      win_command: >
        "C:\ClassAct\ClassAct_Medsim-Installer.exe" /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- /DIR="C:\ClassAct" /LOG="install.log"
      args:
        chdir: C:\ClassAct
